
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Dec 27 2025 19:51:28 IST (Dec 27 2025 14:21:28 UTC)

// Verification Directory fv/updown_counter 

module updown_counter(clk, rst, enable, up_down, count, overflow);
  input clk, rst, enable, up_down;
  output [7:0] count;
  output overflow;
  wire clk, rst, enable, up_down;
  wire [7:0] count;
  wire overflow;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_47, n_48, n_49;
  wire n_50, n_59;
  DFFQX4 \count_reg[6] (.CK (clk), .D (n_50), .Q (count[6]));
  INVXL g1438(.A (n_49), .Y (n_50));
  DFFQX2 \count_reg[7] (.CK (clk), .D (n_48), .Q (count[7]));
  AOI211X1 g1440__2398(.A0 (n_45), .A1 (count[6]), .B0 (n_28), .C0
       (n_47), .Y (n_49));
  MXI2XL g1439__5107(.A (n_42), .B (n_44), .S0 (count[7]), .Y (n_48));
  SDFFQX2 overflow_reg(.CK (clk), .D (n_47), .SI (n_41), .SE
       (count[7]), .Q (overflow));
  SDFFQX2 \count_reg[5] (.CK (clk), .D (n_36), .SI (n_43), .SE
       (count[5]), .Q (count[5]));
  OAI21X1 g1447__4319(.A0 (rst), .A1 (n_15), .B0 (n_39), .Y (n_45));
  NOR2XL g1443__8428(.A (n_16), .B (n_43), .Y (n_44));
  NOR2XL g1444__5526(.A (n_47), .B (n_41), .Y (n_42));
  AOI31XL g1451__6783(.A0 (n_25), .A1 (count[3]), .A2 (n_29), .B0
       (n_32), .Y (n_40));
  CLKINVX1 g1454(.A (n_43), .Y (n_39));
  OAI32XL g1448__3680(.A0 (rst), .A1 (n_33), .A2 (n_22), .B0 (n_26),
       .B1 (count[3]), .Y (n_38));
  OAI211XL g1449__1617(.A0 (n_14), .A1 (n_10), .B0 (n_21), .C0 (n_20),
       .Y (n_37));
  NAND2XL g1450__2802(.A (n_34), .B (n_27), .Y (n_36));
  NOR3X1 g1459__1705(.A (n_34), .B (count[5]), .C (count[6]), .Y
       (n_47));
  AOI31X1 g1458__5122(.A0 (n_7), .A1 (n_30), .A2 (n_33), .B0 (rst), .Y
       (n_43));
  INVXL g1462(.A (n_34), .Y (n_32));
  AOI211X1 g1456__8246(.A0 (n_30), .A1 (n_33), .B0 (rst), .C0 (n_29),
       .Y (n_31));
  NOR3X1 g1455__7098(.A (n_27), .B (count[6]), .C (n_2), .Y (n_28));
  NOR2XL g1457__6131(.A (n_27), .B (n_0), .Y (n_41));
  NOR2XL g1460__1881(.A (n_25), .B (n_23), .Y (n_26));
  NOR2XL g1461__5115(.A (rst), .B (n_19), .Y (n_24));
  NAND3X1 g1463__7482(.A (n_23), .B (n_22), .C (n_29), .Y (n_34));
  INVXL g1465(.A (n_23), .Y (n_21));
  OAI211X1 g1468__4733(.A0 (n_17), .A1 (n_18), .B0 (n_1), .C0
       (count[2]), .Y (n_20));
  NOR4BX1 g1466__6161(.AN (n_8), .B (up_down), .C (count[1]), .D
       (count[2]), .Y (n_23));
  NAND3X1 g1464__9315(.A (n_25), .B (count[3]), .C (count[4]), .Y
       (n_27));
  MXI2XL g1469__9945(.A (n_4), .B (count[1]), .S0 (n_18), .Y (n_19));
  NOR3X1 g1470__2883(.A (n_3), .B (n_17), .C (n_18), .Y (n_33));
  AOI21X1 g1472__2346(.A0 (n_5), .A1 (n_15), .B0 (rst), .Y (n_16));
  NOR3X1 g1467__1666(.A (n_14), .B (n_12), .C (n_9), .Y (n_25));
  OAI32X1 g1475__7410(.A0 (rst), .A1 (enable), .A2 (n_11), .B0 (n_12),
       .B1 (count[0]), .Y (n_13));
  OAI221X1 g1474__6417(.A0 (up_down), .A1 (n_11), .B0 (n_6), .B1
       (count[0]), .C0 (enable), .Y (n_18));
  NAND2BX1 g1477__5477(.AN (n_12), .B (n_9), .Y (n_10));
  NOR2XL g1479__2398(.A (n_12), .B (count[0]), .Y (n_8));
  OAI22X1 g1476__5107(.A0 (up_down), .A1 (count[4]), .B0 (n_6), .B1
       (n_29), .Y (n_7));
  MXI2XL g1480__6260(.A (up_down), .B (n_6), .S0 (count[6]), .Y (n_5));
  OAI22X1 g1478__4319(.A0 (up_down), .A1 (n_4), .B0 (n_6), .B1
       (count[1]), .Y (n_17));
  MXI2XL g1481__8428(.A (count[2]), .B (n_9), .S0 (n_6), .Y (n_3));
  AOI22X1 g1483__5526(.A0 (n_6), .A1 (count[5]), .B0 (up_down), .B1
       (n_2), .Y (n_15));
  AOI22X1 g1482__6783(.A0 (n_6), .A1 (count[3]), .B0 (up_down), .B1
       (n_22), .Y (n_30));
  NAND3X1 g1473__3680(.A (up_down), .B (count[0]), .C (count[1]), .Y
       (n_14));
  NAND2XL g1484__1617(.A (enable), .B (n_1), .Y (n_12));
  NAND2XL g1485__2802(.A (count[5]), .B (count[6]), .Y (n_0));
  INVXL g1492(.A (rst), .Y (n_1));
  CLKINVX1 g1489(.A (count[5]), .Y (n_2));
  INVXL g1493(.A (up_down), .Y (n_6));
  DFFX2 \count_reg[0] (.CK (clk), .D (n_13), .Q (count[0]), .QN (n_11));
  DFFX2 \count_reg[1] (.CK (clk), .D (n_24), .Q (count[1]), .QN (n_4));
  DFFX2 \count_reg[4] (.CK (clk), .D (n_59), .Q (count[4]), .QN (n_29));
  DFFX2 \count_reg[2] (.CK (clk), .D (n_37), .Q (count[2]), .QN (n_9));
  DFFX2 \count_reg[3] (.CK (clk), .D (n_38), .Q (count[3]), .QN (n_22));
  NAND2BX1 g2(.AN (n_31), .B (n_40), .Y (n_59));
endmodule

